### DISCUSSION TITLE
Independent transform polyfill. Always include?

### DISCUSSION THREAD

**Discussion by mattgperry** [motiondivision/motionone#6] [Ideas]
Hi all

Motion Concept C supports animating individual transforms (yey!)

```javascript
// Vanilla
animate(element, { x: 100, rotate: 90 })
```
```jsx
// React
<animated.div initial={{ scale: 0 }} style={{ scale: 1 }} />
```

Unfortunately, this feature relies on a browser supporting `CSS.registerProperty` (o no)

Chromium browsers already support this API, but as for Safari and Firefox - who knows. To take a progressive enhancement approach, Motion will instantly animate in browsers that don't support `CSS.registerProperty`.

I didn't feel like this was quite good enough so over the last couple weeks I've been pottering on tiny number-only polyfill that can animate these values in every browser.

The good news is that it's quite small, around 1kb. But this could grow in size if we chose to support non-numeric CSS variables.

However, relative to the rest of the API, that's quite big. It bumps vanilla Motion from 1.7 to 2.7kb, and Motion for React from 3kb to 4kb.

So there's two approaches we could take. One, always include the polyfill. This will be the better DX. Alternatively, offer the polyfill as an optional extra. This would mean smaller bundle sizes by default but a little more scaffolding for people who wanted to opt-in to this behaviour.

Here's what the API might look like:

```javascript
// Always include polyfill - 2.7kb
import { animate } from "motion"

animate(element, { x: 100 })

// Optional polyfill - 1.7kb + optional 1kb
import { animate, animateNumber, setMotionGlobals } from "motion"

/**
 * Set polyfill. You'd only have to do this once.
 * If polyfill isn't set, independent transform animations
 * become instant transitions
 */
setMotionGlobals({
  independentTransformPolyfill: animateNumber
})

animate(element, { x: 100 })
```

I'm interested in hearing other people's thoughts in this trade-off between bundlesize and DX. What do you think?

**Comment by lunelson** [comment]
Is it possible to include a global stylesheet that accomplishes the creation of the CSS properties that you want to animate, and might this have better browser support?

**Reply by lunelson** [reply]
The support spectrum for CSS `@property` is the same as the `CSS.registerProperty` API I assume, so using CSS won't let you control their ~~inheritability and~~ expected and default units like the better API does; but maybe you can adapt your JS API around simple custom properties (implicitly non-inheritable) with defaults like this:

```css
* {
  --motion-translatex: 0px;
  --motion-translatey: 0px;
  --motion-translatez: 0px;
  --motion-rotatex: 0deg;
  --motion-rotatey: 0deg;
  --motion-rotatez: 0deg;
  --motion-skewx: 0deg;
  --motion-skewy: 0deg;
  --motion-skewz: 0deg;
  --motion-scalex: 1;
  --motion-scaley: 1;
  --motion-scalez: 1;
}
```
